spring.application.name=BibliotecaUnical
logging.level.org.springframework= info

logging.level.root=WARN
logging.level.com.Stefan.BibliotecaUnical=TRACE

spring.datasource.url = jdbc:postgresql://localhost:5432/BibliotecaUnical
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true